//apply
export const APPLY_UPDATE_DATEROOM = 'ORDER_UPDATE_DATEROOM';
export const APPLY_UPDATE_META = 'ORDER_UPDATE_META';
export const APPLY_UPDATE_FORM = 'ORDER_UPDATE_FORM';
export const APPLY_UPDATE_CAPTCHA = 'ORDER_UPDATE_CAPTCHA';



//common
export const UPDATE_SERVERTIME = 'UPDATE_SERVERTIME';
export const UPDATE_META = 'UPDATE_META';
export const UPDATE_ONE_ROOMUSE = 'UPDATE_ONE_ROOMUSE';



//roomtable
export const ROOMTABLE_UPDATE_META = 'ROOMTABLE_UPDATE_META';
export const ROOMTABLE_UPDATE_ROOMTABLES = 'ROOMTABLE_UPDATE_ROOMTABLES';
export const ROOMTABLE_UPDATE_PAGE = 'ROOMTABLE_UPDATE_PAGE';


//entity
export const ENTITY_UPDATE_ROOMS = 'ENTITY_UPDATE_ROOMS';
export const ENTITY_UPDATE_DEPTS = 'ENTITY_UPDATE_DEPTS';
export const ENTITY_UPDATE_LOCKS = 'ENTITY_UPDATE_LOCKS';
export const ENTITY_UPDATE_ORDERS = 'ENTITY_UPDATE_ORDERS';

//
