
export const ENTITY_UPDATE_ROOM = 'ENTITY_UPDATE_ROOM';
export const ENTITY_UPDATE_DEPT = 'ENTITY_UPDATE_DEPT';
export const ENTITY_UPDATE_ORDER = 'ENTITY_UPDATE_ORDER';
export const ENTITY_UPDATE_LOCK = 'ENTITY_UPDATE_LOCK';

export const ROOMTABLE_UPDATE_DATELIST = 'ROOMTABLE_UPDATE_DATELIST';
export const ROOMTABLE_UPDATE_ROOMLIST = 'ROOMTABLE_UPDATE_ROOMLIST';
export const ROOMTABLE_UPDATE_ROOMTABLES = 'ROOMTABLE_UPDATE_ROOMTABLES';


export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const AJAX_LOADING = 'AJAX_LOADING';
export const AJAX_SUCCESS = 'AJAX_SUCCESS';
export const AJAX_ERROR = 'AJAX_ERROR';